import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';
import type { Metadata } from "next";
import { ThemeProvider } from "@mui/material";
import theme from "../../theme";
import AppHeader from './components/app-header/AppHeader';
import "./globals.css";

export const metadata: Metadata = {
  title: "Microsystem - PKMN Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <AppHeader />
            <main style={{paddingTop: '64px', minHeight: '100vh'}}>
              {children}
            </main>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
