services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: ash
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pkmns-database
    ports:
      - "5432:5432"
    volumes:
      - data_sql:/var/lib/postgresql/data       # Persistent data storage
  backend:
    build: ./backend
    ports: 
      - "5000:5000"
    volumes: 
      - ./backend:/src
      - /src/node_modules
    stdin_open: true
    tty: true
    env_file: 
      - ./backend/.env
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports: 
      - "3000:3000"
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    env_file: 
      - ./frontend/.env
volumes:
  data_sql: